apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prefect-server.nameField" . }}
  labels: 
    {{- include "prefect-server.commonLabels" . | nindent 4 }}
{{- with .Values.configMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}